image: clojure:lein
services:
  - postgres:latest

variables:
  POSTGRES_DB: brihaspati_db
  POSTGRES_USER: brihaspati_db
  POSTGRES_PASSWORD: "tara"

stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
   - lein deps
   - lein migrate
   - lein uberjar
  
  artifacts:
    paths:
     - "${CI_PROJECT_DIR}/target/uberjar/brihaspati-0.1.0-SNAPSHOT-standalone.jar"

test:
    stage: test
    script:
     - lein migrate-test
     - lein test


deploy:
  stage: deploy
  script:
   - "mkdir sshkey"
   - "printenv SSH_PRIVATE_KEY > ./sshkey/app-key.pem"
   - "chmod 700 ./sshkey"
   - "chmod 400 ./sshkey/app-key.pem"
   - "scp -i ./sshkey/app-key.pem -o StrictHostKeyChecking=no ${CI_PROJECT_DIR}/target/uberjar/brihaspati-0.1.0-SNAPSHOT-standalone.jar ubuntu@ec2-13-232-192-167.ap-south-1.compute.amazonaws.com:" 
   - "ssh -i ./sshkey/app-key.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-232-192-167.ap-south-1.compute.amazonaws.com 'sudo chmod 700 brihaspati-0.1.0-SNAPSHOT-standalone.jar   && sudo systemctl stop execute-uberjar.service && sudo systemctl start execute-uberjar.service' "
