version: '3.0'
services:
  postgres:
    restart: 'always'
    environment:
      - "POSTGRES_USER=brihaspati_db"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=tara"
    image: 'postgres:alpine'
  brihaspati_server:
    restart: 'always'
    ports:
      - '8080:8080'
    environment:
      - "DB_USER=brihaspati_db"
      - "DB_NAME=postgres"
      - "DB_TYPE=postgresql"
      - "DB_PORT=5432"
      - "PORT=8080"
      - "DB_PASSWORD=tara"
      - "DB_HOST=postgres"
    build:
      context: .
      dockerfile: Dockerfile
