version: "3"
services:
 dev_db:
  image:  postgres:11-alpine
  environment:
   POSTGRES_USER: brihaspati_db
   POSTGRES_PASSWORD: tara
  ports:
    - "7001:5432"
 brihaspati_server:
    restart: 'always'
    ports:
      - '8080:8080'
      - '7001:7001'
    env_file: 
      - env/db-test.env
    build:
      context: .
      dockerfile: Dockerfile

