name: Clojure CI


on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:latest
        ports:
          - 7001:5432
        env:
          POSTGRES_DB: brihaspati_db
          POSTGRES_USER: brihaspati_db
          POSTGRES_PASSWORD: "tara"

    steps:
    - name: set the env variables
      env: 
       DB_TYPE: postgresql
       DB_NAME: brihaspati_db
       DB_USER: brihaspati_db
       DB_PASSWORD: tara
       DB_PORT: 7001
       DB_HOST: localhost
       port: 9001
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Make migrations
      run: lein migrate
    - name: Build the uberjar
      run:  lein uberjar
    - uses: actions/upload-artifact@master
      with:
        name: brihaspati-0.1.0-SNAPSHOT-standalone.jar
        path: target/uberjar

