name: Clojure CI


on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:latest
        ports:
          - 7001:5432
        env:
          POSTGRES_DB: brihaspati_db
          POSTGRES_USER: brihaspati_db
          POSTGRES_PASSWORD: "tara"

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
      
    - name: Set the environment variables and Make migrations
      env: 
       DB_TYPE: postgresql
       DB_NAME: "brihaspati_db"
       DB_USER: "brihaspati_db"
       DB_PASSWORD: "tara"
       DB_PORT: "7001"
       DB_HOST: "localhost"
       port: "9001"
    - name: check the env variables
       run: printenv | grep DB
      run: lein migrate
    - name: Build the uberjar
      run:  lein uberjar
    - uses: actions/upload-artifact@master
      with:
        name: brihaspati-0.1.0-SNAPSHOT-standalone.jar
        path: target/uberjar

