name: Clojure CI


services: 
  postgres:
    image: postgres:latest
    ports:
      - 7001:5432
    env:
      POSTGRES_DB: brihaspati_db
      POSTGRES_USER: brihaspati_db
      POSTGRES_PASSWORD: "tara"

variables:

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Make migrations
      run: lein migrate
    - name: Build the uberjar
      run:  lein uberjar
    - uses: actions/upload-artifact@master
      with:
        name: brihaspati-0.1.0-SNAPSHOT-standalone.jar
        path: target/uberjar

