name: Clojure CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Make migrations
      run: lein migrate
    - name: Build the uberjar
      run:  lein uberjar
    - uses: actions/upload-artifact@master
      with:
        name: brihaspati-0.1.0-SNAPSHOT-standalone.jar
        path: target/uberjar

